### ISSUE TITLE
หาตัวจับเวลาการทำงานโค้ดให้หน่อย

### ISSUE THREAD

**Issue by Pongkarm** [Pongkarm/Data_Structures#4]
ตัวจับเวลาที่คอมพิวเตอร์ทำงานครูบอกว่ามันจะมีอยู่ตัวนึงตุณ อภิสักก์ คงภักดี ทำให้ด้วยนะครับ เสร็จแล้วpull requsets มา

**Comment by Kong19565** [comment]
ได้ครับ

**Comment by Kong19565** [comment]
เรียบร้อยแล้วครับ
